package us.rdodd.digital.i8088;

public enum SimStates {
   POWERUP, RESET0, RESET1, RESET2, RESET3, RESET4, FETCH0, FETCH1, FETCH2, 
   BUSCYCLE0, BUSCYCLE1, BUSCYCLE2, BUSCYCLE3, BUSCYCLE4,
   UNDEFINED, ERROR
}
